SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT I.USER_ID) AS USERS

FROM
    USER_INFO AS I
    
JOIN
    ONLINE_SALE AS S USING (USER_ID)
    
WHERE
    I.GENDER IS NOT NULL

GROUP BY
    YEAR, MONTH, I.GENDER

ORDER BY
    YEAR, MONTH, I.GENDER;