SELECT
  YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
  ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO

FROM
  ONLINE_SALE AS O

JOIN
  USER_INFO AS U USING (USER_ID)

WHERE U.JOINED LIKE '2021%'

GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)

ORDER BY YEAR, MONTH;