SELECT
  U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM
  USED_GOODS_BOARD AS B

JOIN
  USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID

WHERE
  B.STATUS = 'DONE' AND 
  USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
  )

GROUP BY U.USER_ID, U.NICKNAME

ORDER BY TOTAL_SALES;